
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ID INTLIT\n    Primary : INTLIT \n            | '(' Primary ')'\n    "
    
_lr_action_items = {'INTLIT':([0,3,],[2,2,]),'(':([0,3,],[3,3,]),'$end':([1,2,5,],[0,-1,-2,]),')':([2,4,5,],[-1,5,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Primary':([0,3,],[1,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Primary","S'",1,None,None,None),
  ('Primary -> INTLIT','Primary',1,'p_Primary','analisis.py',31),
  ('Primary -> ( Primary )','Primary',3,'p_Primary','analisis.py',32),
]
